### ISSUE TITLE
Show victim name for voter

### ISSUE THREAD

**Issue by JarnoVgr** [MrGreenGaming/MTA-Resources#101]
I once changed this to show the victim name in the voting process for 'random shit'. Why was this reverted? Thought it was a cool addition.

**Comment by AfuSensi** [comment]
This was because if names are showing, people with friends will get warned or favouritism happens.
For instance, if player a is in the vote, people warn player a to stand still or drive fast depending on the possible vote, it was becoming pretty lame imo.

I dont remember who reverted it, but i do remember i was talking with sdk about it at the time.

**Comment by EsDeKa** [comment]
I was thinking about this and an easy solution for the favouritism is showing the vote names to everyone alive as well. But then they get warned too which could make it even lamer.

@JarnoVgr do you want people to see the name while voting? Or show the name when the vote is decided

**Comment by JarnoVgr** [comment]
Never thought favouritism would really become a problem. But if that's the case then it would still be nice to see the name when the vote action is performed.
