### ISSUE TITLE
MIX: New gamemode ideas

### ISSUE THREAD

**Issue by JarnoVgr** [MrGreenGaming/MTA-Resources#209]
I really think some GTA Online freemode events gamemodes can be fun in the MIX server. Also added one from the classic MTA days (Cat vs Mice).
- [Penned in](https://youtu.be/96sgHBzC3Cc): Players are supposed to stay within a moving area. Last one to stay alive wins.
- [Moving target](https://youtu.be/-CU9PZUDcFI?t=1245): One player is supposed to drive to a destination in a heavy (or stupid) vehicle and the rest needs to destroy him before reaching it.
- [Longest jump](https://youtu.be/Oa3_sHTeH5c?t=609): Perform the longest stunt jump within timeframe and land correctly. Will work best in custom maps which have a stunt area.
- Collect checkpoints: 100 checkpoints are spread out in an area (either air or land) and players need to collect as many as they can. Once collected the checkpoint disappears. Players with most collected win. To make it fun for new players, it's possible to also reward with GC for every collect. This also exists in GTA Online but can't find it on YT.
- Cat vs Mice: All players except the cat (a Rhino tank for example) have a golfcart or other shitty vehicle and they need to stay alive within a timeframe. Many variations can be made.

**Comment by Megas97** [comment]
Longest Jump cought my eye. Maybe call it "Stunts" and give huge GC rewards for a completed stunt (ofcourse ammount would depend on the difficulty of the stunt itself)?

**Comment by f1madkiller** [comment]
We could try some of these for the 10 year Mr Green event if any work add a 3rd server with things like this or remove a few gamemodes (RTF) and replace it with a new mode

**Comment by BobT123** [comment]
i think some of that can be done as map

**Comment by Bierbuikje** [comment]
Maybe we can make a 'custom' mode. If these modes are added to the server there are a few maps of them and adding it as a separate mode may be very repetitive if it plays the same map every 30 minutes. If all modes are combined in one 'custom' mode there is more variety. If a mode has a lot of maps after a while it can be added as a separate mode. Each mode could have standardized scripts which mapmakers can include in their maps.

I also thought about new modes for mix. One is a dogfight mode which is similar to shooter mode but with Rustlers or Hydra's to perform dogfight in air. Another one is an endurance race (can take up to 1 hour for a map) but to make it interesting for players who join later some sort of 'race sections' need to be added. Each section is a route of checkpoints which take 5 to 10 minutes and all the sections combined is the whole map. If a player completes a section his completion time will be saved to see which player was the fastest in that section and it gets an amount of gc for completing the section. When the map ends the players get a bonus if they had the fastest time in a section and if they finished the map. I'm aware the endurance mode may not be suitable for Mr.Green because it may be boring for newly joined players and other players do not enjoy such a long map at all. And on top of that they may drive alone for large parts of the map.
