### ISSUE TITLE
No high DPI support

### ISSUE THREAD

**Issue by JarnoVgr** [MrGreenGaming/MTA-Resources#376]
It would be great if HUD and UI elements scaled properly on high resolutions such as 4K.

The new radar looks fine. Most other UI elements do not.

**Comment by Bierbuikje** [comment]
I would like to combine this with a whole make over for all HUD/UI elements to make the appearance more uniform in the same style. What I was thinking of was making the HUD/UI appearance more like a gta5 experience. The following I had in mind:

- [ ] New design for rankboard (more like formula 1 ranking board: https://i.ytimg.com/vi/6yXvIbKXehw/maxresdefault.jpg)
- [ ] Different place for the greencoins counter or only make it pop up when greencoins balance changes
- [ ] Remove next map window, by default disabled I believe (not sure) but just remove it anyway
- [ ] Race delay indicator can stay
- [ ] Different place for the speed-o-meter, more in a corner somewhere
- [ ] Different place for the fps/ping statistics, also more in a corner
- [ ] Replace old-hud, new-hud and sp-hud with a gta5-hud. New-hud is already very much like the gta-5 hud but can be edited a bit more I think.
- [ ] Remove new radar (unpopular opinion) because of it's drag on clients performance. In some cases it takes up to 50% of the client's cpu power. I believe it has a significant impact on fps. Only keep the old radar.
- [ ] Remove the race progress bar, also has a relatively large impact on cpu. To be replaced with the formula 1 rankboard.
- [ ] Put the health and nitro bar somewhere near the old radar.
- [ ] Put the map countdown somewhere else
- [ ] Change the 'next map window' and 'toptimes window' (triggered with F5) to windows in the gta5 style
- [ ] A separate UI for finishing which shows the stats obtained during the race (vague, yes)
- [ ] Also I would like to have some sort of notification section above the radar like in gta5 where notifications pop-up when you have overtaken someone or someone finished the race. This part could also be used for other notifications like if you received a message or the server wants to notify you of something.
- [ ] Change the mrgreengaming.com website ad below the radar to something that fits the style of this new HUD/UI

Maybe more things come along the way. But the main idea is to make everything fit in with each other and make it more modern style. If this is all implemented then it may take a while to do of course.

**Comment by JarnoVgr** [comment]
I fully agree that the HUD needs an overhaul. I do not fully agree with all mentioned propositions (radar for example). But a San Andreas and GTA5 HUD crossover could really work. We already have that, but there are loads of UI elements which do not fit that style at this moment.

Maybe create a new issue with your propositions? :)

**Comment by Bierbuikje** [comment]
I'll do that and we can discuss every hud/ui change there and what it should look like. About the new radar I already feared that you would disagree. It is indeed a really nice radar but it has also a significant impact on performance. We could think about what to do with it later, if anything will be done with it at all.

**Comment by f1madkiller** [comment]
http://cdn.newsapi.com.au/image/v1/914b1a6437c2d29fb5af1be8f51e473f may I suggest use the new 2018 hud from F1 as you can have like map name where VSC is and mr green logo where on track hazard is as it seems clearer than the 2017 one IMO just thought i'd give you and Ywa another option too look at
