### ISSUE TITLE
Multiple bad practice SQL queries that broke

### ISSUE THREAD

**Issue by JarnoVgr** [MrGreenGaming/MTA-Resources#382]
This is to track broken SQL queries and whether they've been fixed or not.

- [x] `WARNING: [admin]\maptools\mm.lua:85; dbExec failed; (1364) field 'forumId' doesn't have a default value` Fix: set default value of forumid to 0

**Comment by Bierbuikje** [comment]
- [ ] `WARNING: [gameplay]\gcshop\modshop\modshop_s.lua:952: dbExec failed; (1364) field 'slot0' doesn't have a default value`

**Comment by Bierbuikje** [comment]
- [ ] `WARNING: [gameplay]\gcshop\teams\teams_s.lua:136 dbExec failed; (1406) Data too long for column 'tag' at row 1`
- [ ] `WARNING: [gameplay]\gcshop\teams\teams_s.lua:138 dbExec failed; (1452) Cannot add or update a child row: a foreign key constraint fails ('mrgreen_mtasrvs', 'team_members', CONSTRAINT 'Team members' FOREIGN KEY ('teamid') REFERENCES 'team' ('teamid') ON DEL`

Last part of debug info missing because of the sentence length.

**Comment by JarnoVgr** [comment]
Will fix it tomorrow

**Comment by EsDeKa** [comment]
Fixed the `Data too long for column 'tag'` warning by changing utf8_general_ci to utf8mb4_general_ci
Teams with weird characters can be created again (but I'm not sure they display correctly)

**Comment by JarnoVgr** [comment]
Are there any errors left for me to fix?

**Comment by JarnoVgr** [comment]
Closing this. I assume there are no problems anymore. @EsDeKa @Bierbuikje
